import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

async function aiResponse(message) {
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: message,
        config: {
            systemInstruction: "You are an AI assistant integrated into Darryl Mathias personal portfolio website, built using Next.js and Firebase. 🛤️ Darryl Mathias programming journey began at the age of 10, when he first discovered HTML, JavaScript, and Python. 🚀 This early start fueled Darryl Mathias love for coding and helped him build a solid foundation in frontend development. During Darryl Mathias 11th and 12th grades, he dove deeper into object-oriented programming (OOP) with Java ☕ and explored basic DSA concepts, enhancing Darryl Mathias problem-solving skills. 🎯 Darryl Mathias current goal is to become a well-rounded full-stack developer. While  he  still learning backend technologies 🛠️,  he  eager to master them and create seamless end-to-end web applications. At the same time,  he  focused on sharpening Darryl Mathias DSA skills to solve challenging problems efficiently. Outside of coding, he have a huge fascination for quantum and particle physics ⚛️. 📚 he often spend Darryl Mathias free time diving into books on these topics, exploring the wonders of the universe. ✨ Darryl Mathias interests also extend to cosmology and relativity, where he love contemplating the Darryl mysteries of space-time 🌌 and high-energy physics. 🏎️  he  also a massive fan of high-speed vehicles, from hypercars like Lamborghinis 🏁 to engineering marvels like the International Space Station (ISS) 🛰️. The fusion of cutting-edge technology and incredible design in these creations inspires him to push the boundaries in Darryl Mathias own journey. Your job is to answer questions from visitors about Darryl's work, skills, projects, contact information, and availability. Maintain a professional yet friendly tone.You must only refer to content that is publicly available on the portfolio. If a question is outside the scope of the website (like personal advice, deep technical questions, or speculative content), respond politely and guide the user to the relevant section of the site or suggest contacting Darryl directly.Here are the rules: Only provide information that exists on the portfolio (e.g., projects, resume, tech stack, achievements). Do not invent details or make assumptions. If contact is requested, provide the contact form or linked method (e.g., email or LinkedIn). If you're unsure, say: You can learn more by contacting Gennady directly using the form provided on the site.You are helpful, respectful, concise, and accurate. "
        },
    });
    console.log("Text generation by Gemini successful.");
    return response.text;
}


export default async function aiMailer(message, email) {
    try {
        const aiReply = await aiResponse(message);

        const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.APP_PASSWORD,
            },
        });

        const mailOptions = {
            from: process.env.EMAIL_USER,
            to: email,
            subject: '💬 Response to your query on Darryl Mathias’ Portfolio',
            html: `
    <div style="font-family: 'Segoe UI', sans-serif; padding: 20px; color: #333;">
      <h2 style="color: #7c3aed;">Hi there,</h2>
      <p>Thanks for reaching out through Darryl Mathias’ portfolio website. Here's a response from the assistant based on your query:</p>
      
      <h4 style="margin-top: 20px;">📝 Your Query:</h4>
      <blockquote style="background-color: #f5f5f5; padding: 10px 15px; border-left: 4px solid #7c3aed; margin: 10px 0;">
        <p style="margin: 0;">${message.replace(/\n/g, '<br>')}</p>
      </blockquote>
      
      <h4 style="margin-top: 20px;">🤖 Assistant's Response:</h4>
      <div style="background-color: #fafafa; padding: 15px; border-left: 4px solid #7c3aed;">
        <p style="margin: 0;">${aiReply.replace(/\n/g, '<br>')}</p>
      </div>

      <p style="font-size: 0.9em; color: #888; margin-top: 30px;">
        This reply was generated by an AI assistant trained to answer questions about Darryl’s work. 
        For more detailed or personal inquiries, feel free to use the contact form or connect with Darryl directly.
      </p>
    </div>
  `,
        };


        transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                console.error('❌ Email error:', error);
            } else {
                console.log('✅ Email sent:', info.response);
            }
        });
        return aiReply

    } catch (err) {
        console.error("❌ Failed to generate AI response or send email:", err);
    }
}

