import * as React from 'react';
import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
  Tailwind,
  Link,
} from '@react-email/components';

export default function AiResponseEmail({ userQuery, aiResponse }) {
  const previewText = `Response from Darryl's AI Assistant`;

  return (
    <Html>
      <Head />
      <Preview>{previewText}</Preview>
      <Tailwind>
        <Body className="bg-[#f6f9fc] my-auto mx-auto font-sans px-2">
          <Container className="border border-solid border-[#eaeaea] rounded-xl my-[40px] mx-auto p-[20px] max-w-[600px] bg-white shadow-xl">
            <Section className="mt-[16px] text-center">
              <Text className="text-[#8b5cf6] text-[24px] font-bold m-0 tracking-tight">Darryl Mathias</Text>
            </Section>

            <Section className="bg-[#fcf8ff] rounded-lg p-[20px] my-[24px] border border-solid border-[#e9d5ff]">
              <Text className="text-[#333333] text-[15px] leading-[24px] m-0 whitespace-pre-wrap">
                {aiResponse}
              </Text>
            </Section>

            <Hr className="border border-solid border-[#eaeaea] my-[26px] mx-0 w-full" />

            <Text className="text-[#666666] text-[13px] leading-[20px] mb-[8px]">
              This reply was generated by an AI assistant trained to answer questions about Darryl’s work.
            </Text>
            <Text className="text-[#666666] text-[13px] leading-[20px] m-0">
              For more detailed or personal inquiries, feel free to connect with Darryl directly on{' '}
              <Link href="www.linkedin.com/in/darryl-mathias-020241317/" className="text-[#8b5cf6] underline">
                LinkedIn
              </Link>{' '}
              or check out his{' '}
              <Link href="https://darrylmathias.tech" className="text-[#8b5cf6] underline">
                portfolio
              </Link>.
            </Text>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
}
