name: Continuos Deployment Notifier

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Svix of new push
        run : |
          curl -X POST "https://api.eu.svix.com/api/v1/app/portfolio-consumer/msg/" \
          -H  "Accept: application/json" \
          -H  "Content-Type: application/json" \
          -H  "Authorization: Bearer ${{ secrets.SVIX_API_KEY }}" \
          -d '{"eventType": "github.push", "eventId": "${{ github.sha }}", "payload": {"type": "github.push", "branch": "${{ github.ref_name }}", "commit": "${{ github.sha }}" }}'
        
